# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/rultor-image:1.9.1
assets:
  tokenscript.txt: yegor256/objectionary-secrets#marketplace.token.sh
install: |
  curl -s "https://get.sdkman.io" | bash
  source "$HOME/.sdkman/bin/sdkman-init.sh"
  sdk version
  sdk install gradle 8.1.1
merge:
  script: |
    gradle wrapper
    gradle build
release:
  pre: false
  script: |
    source ../tokenscript.txt
    sed -i -e "s/0.0.0/${tag}/" src/main/resources/META-INF/plugin.xml
    sed -i -e "s/0.0.0/${tag}/" gradle.properties
    gradle wrapper
    gradle publishPlugin --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'
