# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: Build Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v4

      # 2. Set up Java (use the version your plugin targets)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Cache Gradle’s wrapper and dependencies
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}

      # 4. Build the plugin ZIP
      - name: Build IntelliJ Plugin
        run: ./gradlew buildPlugin --no-daemon

      # 5. Publish the generated ZIP as an artifact
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: eo-intellij-plugin
          path: build/distributions/*.zip
