# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: Java CI
on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          # see https://www.jetbrains.com/idea/download/previous.html
          # and https://www.jetbrains.com/intellij-repository/snapshots/
          - IDEA_VERSION: IU-LATEST-EAP-SNAPSHOT
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build with Gradle
        run: gradle wrapper; gradle build --stacktrace
        env: ${{ matrix.env }}