# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Print Java version
        run: java -version

      - name: Build & package
        run: mvn -B clean install
