# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        env:
          # see https://www.jetbrains.com/idea/download/previous.html
          # and https://www.jetbrains.com/intellij-repository/snapshots/
          - IDEA_VERSION: IC-2020.3
          - IDEA_VERSION: IC-2021.2.4
          - IDEA_VERSION: IC-2021.3.3
          - IDEA_VERSION: IC-2022.1.1
          - IDEA_VERSION: IU-LATEST-EAP-SNAPSHOT
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
      - run: gradle wrapper; gradle build
        env: ${{ matrix.env }}
