# SPDX-FileCopyrightText: Copyright (c) 2021-2025 Stepan Strunkov
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: qulice
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  qulice:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 21
      - run: |
          mvn com.qulice:qulice-maven-plugin:check -Dqulice.excludes=pmd:.* -Dqulice.license=file:LICENSE.txt
