name: Code quality
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - run: |
          mvn com.qulice:qulice-maven-plugin:check -Dqulice.excludes=pmd:.* -Dqulice.license=file:LICENSE.txt
