name: Build
on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [test]
jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
    - name: Verify Plugin on IntelliJ Platforms
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ide-versions: |
          ideaIC:2019.3